# Generated by Django 5.0.6 on 2024-06-27 14:05

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mainpagecontent_crop_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpagecontent',
            name='header_image',
            field=image_cropping.fields.ImageCropField(upload_to='header/', verbose_name='Header image'),
        ),
    ]
